### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by tagTG**
“This project is tested with BrowserStack.”

### CODE REVIEW

**Comment by p32929** [comment]
Pardon my ignorance, but I have never heard of browserstack, & not sure what difference does it make to the end users whether or not it is tested by browserstack. Would you please explain a little bit?

**Comment by tagTG** [comment]
i want to test with browser stack.. so please merge it

**Comment by p32929** [comment]
Please make a fork and run the deploy command. then you'll be able to test it with the github page link

**Comment by tagTG** [comment]
actually i want to use it with browser stack with a lot of features thats
why

**Comment by tagTG** [comment]
check this

   - You will need to submit and merge a PR to the project. The PR has to
   add the following text to your readme.md file: “This project is tested with
   BrowserStack
   <https://email.browserstack.com/c/eJwlzE2OgzAMQOHTlF1QHPLHImepnNhpES2UGIo0px9Gs376Hifw3lhnhxg6Si47Ct2U_ABBYzAjVI93oGiyHp02OTosoCEYY3UvE_E8bao23g5edlVJfVY6hFF2UG-clkE9GvOiQvXZ-uwzqa91ZG5W89Vf_WXlSSxzX9Z390zaxlKII8Tg0OtgwWCIFewITmeP3Sud59nntp7CTXYs_7Klz9F-VsF54Wv-PaThX_gFdc1GyQ>
   .”



   - The PR has to be dated post the date of your request for sponsorship.

**Comment by p32929** [comment]
I understand your point. That's why I'm suggesting that you make a fork and run the deploy command.

**Comment by p32929** [comment]
In that case, just clone it and push it into one of your own repositories. After that, you can test it

**Comment by tagTG** [comment]
i dnt know how to do this.. please do it from your side

**Pull request closed without merging**
